[package]
name = "overlay"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

description = "A way to create game overlays"
documentation = "https://docs.rs/overlay"
repository = "https://github.com/maroider/overlay"

readme = "README.md"
keywords = ["overlay"]
categories = ["gui"]

license = "MIT OR APACHE-2.0"

[dependencies]
winit = "0.20.0-alpha5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["windef", "winuser"] }

[dev-dependencies]
env_logger = "0.7.1"
imgui = "0.2.1"
imgui-wgpu = "0.4.1"
imgui-winit-support = { version = "0.2.1", default-features = false, features = ["winit-20"] }
wgpu = "0.4.0"
winit = "0.20.0-alpha5"
